{% set name = "lensfunpy" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/letmaik/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 69ac4d0e1c59a57e9bbd0da62b0455c37d954bc5afe40f155e86847d4b8751b6
  patches:
    - 0002_remove_osx_condition.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - pip
    - python
    - lensfun <0.3.95
    - numpy
  run:
    - {{ pin_compatible('numpy') }}
    - lensfun <0.3.95
    - {{ pin_compatible('lensfun') }}
    - python
    - cython
    - scipy

test:
  imports:
    - lensfunpy

about:
  home: https://letmaik.github.io/lensfunpy/index.html
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "lensfunpy is an easy-to-use Python wrapper for the lensfun library."
  doc_url: https://pypi.org/project/lensfunpy/
  dev_url: https://github.com/letmaik/lensfunpy

extra:
  recipe-maintainers:
    - oblute
    - mwilson8
    - rluria14
